version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - backend
    - frontend
  backend:
    image: hsjhita1/backend:latest
    build: ./spring-petclinic-rest
    ports:
    - target: 9966
      published: 9966
    environment:
    - dburl=${DBURL}
    - dbuser=${DBUSER}
    - dbpass=${DBPASS}
  frontend:
    image: hsjhita1/frontend:latest
    build: ./spring-petclinic-angular
    ports:
    - target: 4200
      published: 4200
    depends_on:
    - backend
